# Generated by Django 3.2.6 on 2022-03-08 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='mock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='front.mocktest'),
            preserve_default=False,
        ),
    ]
