# Generated by Django 3.2.6 on 2022-03-11 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='test_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='mock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mocker', to='front.mocktest'),
        ),
    ]
